### ISSUE TITLE
Cannot find package 'devalue'

### ISSUE THREAD

**Issue by soupman99** [simonnepomuk/monorepo#8]
@simonnepomuk Thanks so much for the svelte firebase lib!

I'm running into a similar issue to #3 

Here's the error.  I tried adding it to the package.json in src and functions but no success. Any idea what's causing this?
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'devalue' imported from /workspace/.firebase/server/index.js

**Comment by simonnepomuk** [comment]
Hey, I'm not really actively maintaining this. Due to some regulatory issues I'm not able to use firebase for the project that I intended to use it on, so I'm not really too inclined to spend time on this. But I think the folks @ firebase are spending some time to get SvelteKit to work with their framework support. SvelteKit adapters for Firebase should hopefully be obsolete when https://github.com/firebase/firebase-tools/pull/5525 is merged
